{% set name = "azure-mgmt-cosmosdb" %}
{% set version = "9.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4678bf042bdc208aa24fca71767ac29b6f2a2722ac7872608371a5922f3b6c37

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=77.0.3
  run:
    - python
    - msrest >=0.7.1
    - azure-mgmt-core >=1.6.0
    - typing-extensions >=4.6.0

test:
  imports:
    - azure.mgmt.cosmosdb
    - azure.mgmt.cosmosdb.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Cosmos DB Management Client Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    This is the Microsoft Azure Cosmos DB Management Client Library.
  doc_url: https://github.com/Azure/azure-sdk-for-python
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - awvwgk
